# build with: docker build -f test/DependencyTesting/Dockerfile.base -t nbm-base .
# run with: docker run -it nbm-base
# test compile: nbm no_eval -o out

FROM debian:bookworm-slim

WORKDIR /test-files

# copy binary to container's PATH
COPY dist/nbm /usr/local/bin/nbm    

# copy zero-dependency NBM file to container (should compile)
COPY test/DependencyTesting/no_eval.nbm /test-files/no_eval.nbm

# copy GCH-dependant NBM file to container (should not compile)
COPY test/DependencyTesting/with_eval.nbm /test-files/with_eval.nbm

CMD ["/bin/bash"]