# build with: docker build -f test/DependencyTesting/Dockerfile.ghcpdf -t nbm-ghcpdf .
# run with: docker run -it nbm-ghcpdf
# test compile: nbm with_eval -o out -w -p

FROM debian:bookworm-slim

# install only GHC and a minimal TeX distribution
RUN apt-get update && apt-get install -y \
    ghc \
    texlive-latex-base \
    texlive-fonts-recommended

WORKDIR /test-files

# copy binary to container's PATH
COPY dist/nbm /usr/local/bin/nbm    

# copy zero-dependency NBM file to container (should compile)
COPY test/DependencyTesting/no_eval.nbm /test-files/no_eval.nbm

# copy GCH-dependant NBM file to container (should compile)
COPY test/DependencyTesting/with_eval.nbm /test-files/with_eval.nbm

CMD ["/bin/bash"]